/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sample.rpc.protocol;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Calculator {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Calculator\",\"namespace\":\"sample.rpc.protocol\",\"types\":[],\"messages\":{\"add\":{\"request\":[{\"name\":\"a\",\"type\":\"int\"},{\"name\":\"b\",\"type\":\"int\"}],\"response\":\"int\"},\"subtract\":{\"request\":[{\"name\":\"a\",\"type\":\"int\"},{\"name\":\"b\",\"type\":\"int\"}],\"response\":\"int\"},\"multiply\":{\"request\":[{\"name\":\"a\",\"type\":\"int\"},{\"name\":\"b\",\"type\":\"int\"}],\"response\":\"int\"},\"divide\":{\"request\":[{\"name\":\"a\",\"type\":\"int\"},{\"name\":\"b\",\"type\":\"int\"}],\"response\":\"int\"}}}");
  /**
   */
  int add(int a, int b) throws org.apache.avro.AvroRemoteException;
  /**
   */
  int subtract(int a, int b) throws org.apache.avro.AvroRemoteException;
  /**
   */
  int multiply(int a, int b) throws org.apache.avro.AvroRemoteException;
  /**
   */
  int divide(int a, int b) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends Calculator {
    public static final org.apache.avro.Protocol PROTOCOL = sample.rpc.protocol.Calculator.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void add(int a, int b, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void subtract(int a, int b, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void multiply(int a, int b, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void divide(int a, int b, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
  }
}